package com.b3.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;

/**
 * UserProfile Entity
 * 
 * Represents the single demo user in the B3 application.
 * This is a JPA entity that maps to the "user_profile" table in SQLite.
 * 
 * Design Note: B3 uses a single-user model (no authentication required).
 * The demo user always has profileId = 1, allowing BRIX to personalize
 * coaching based on equipment, fitness level, and goals without login complexity.
 * 
 * @author Ben Rickert
 * @version 1.0
 */
@Entity  // Marks this class as a JPA entity (will be mapped to a database table)
@Table(name = "user_profile")  // Specifies the exact table name in the database
public class UserProfile {

    // ==================== Fields (Database Columns) ====================

    /**
     * Primary Key - Unique identifier for the user profile
     * Auto-generated by the database using IDENTITY strategy (auto-increment)
     */
    @Id  // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Database auto-increments this value
    @Column(name = "profile_id")  // Maps to "profile_id" column in database
    private Long profileId;

    /**
     * Display Name - User's chosen name for the app
     * Validation: Required, 2-50 characters
     * Used in: Home screen greeting, BRIX messages
     */
    @NotBlank(message = "Display name is required")  // Cannot be null or empty string
    @Size(min = 2, max = 50, message = "Display name must be between 2 and 50 characters")  // Length constraint
    @Column(name = "display_name", nullable = false, length = 50)  // Database column config
    private String displayName;

    /**
     * Age - User's age in years
     * Validation: Required, 13-120 (reasonable range)
     * Used by: BRIX to adjust workout intensity recommendations
     */
    @NotNull(message = "Age is required")  // Cannot be null
    @Min(value = 13, message = "User must be at least 13 years old")  // Minimum age 13
    @Max(value = 120, message = "Age must be realistic")  // Maximum age 120
    @Column(name = "age", nullable = false)  // Cannot be null in database
    private Integer age;

    /**
     * Fitness Level - User's self-assessed fitness level
     * Valid values: "Beginner", "Intermediate", "Advanced"
     * Used by: BRIX to select appropriate workout difficulty
     */
    @NotBlank(message = "Fitness level is required")
    @Pattern(regexp = "Beginner|Intermediate|Advanced",  // Only these exact values allowed
             message = "Fitness level must be Beginner, Intermediate, or Advanced")
    @Column(name = "fitness_level", nullable = false, length = 20)
    private String fitnessLevel;

    /**
     * Primary Goal - User's main fitness objective
     * Valid values: "Strength", "Cardio", "Flexibility", "Weight Loss"
     * Used by: BRIX to prioritize workout categories (e.g., more cardio if goal is Weight Loss)
     */
    @NotBlank(message = "Primary goal is required")
    @Pattern(regexp = "Strength|Cardio|Flexibility|Weight Loss",  // Enum-like constraint
             message = "Invalid primary goal")
    @Column(name = "primary_goal", nullable = false, length = 30)
    private String primaryGoal;

    /**
     * Equipment - Available workout equipment (comma-separated)
     * Examples: "Dumbbells,Resistance Bands", "None", "Dumbbells,Pull-up Bar"
     * Used by: Workout filtering (only show workouts user can actually do)
     * Optional: User might only do bodyweight exercises
     */
    @Column(name = "equipment", length = 200)  // Optional field (nullable = true by default)
    private String equipment;

    /**
     * Weekly Goal Days - Target number of workout days per week
     * Validation: 1-7 days
     * Used by: Progress tracking, consistency calculations
     * Example: If goal is 4 days/week and user hits 3, that's 75% consistency
     */
    @NotNull(message = "Weekly goal days is required")
    @Min(value = 1, message = "Weekly goal must be at least 1 day")
    @Max(value = 7, message = "Weekly goal cannot exceed 7 days")
    @Column(name = "weekly_goal_days", nullable = false)
    private Integer weeklyGoalDays;

    /**
     * Created At - Timestamp when profile was first created
     * Auto-populated by @PrePersist callback (see onCreate method below)
     * updatable = false means this never changes after initial insert
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Updated At - Timestamp when profile was last modified
     * Auto-updated by @PreUpdate callback (see onUpdate method below)
     * Used for: Tracking when user last changed their preferences
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ==================== Constructors ====================

    /**
     * Default Constructor (Required by JPA)
     * JPA uses this to create entity instances when loading from database
     * Never call this directly - use the parameterized constructor instead
     */
    public UserProfile() {
        // No initialization needed - JPA will set fields via reflection
    }

    /**
     * Parameterized Constructor - Creates a new UserProfile with all required fields
     * 
     * @param displayName User's display name (2-50 chars)
     * @param age User's age (13-120)
     * @param fitnessLevel "Beginner", "Intermediate", or "Advanced"
     * @param primaryGoal "Strength", "Cardio", "Flexibility", or "Weight Loss"
     * @param equipment Comma-separated list (e.g., "Dumbbells,Bands") or null
     * @param weeklyGoalDays Target workout days per week (1-7)
     */
    public UserProfile(String displayName, Integer age, String fitnessLevel, 
                       String primaryGoal, String equipment, Integer weeklyGoalDays) {
        this.displayName = displayName;
        this.age = age;
        this.fitnessLevel = fitnessLevel;
        this.primaryGoal = primaryGoal;
        this.equipment = equipment;
        this.weeklyGoalDays = weeklyGoalDays;
        // Note: createdAt and updatedAt are set automatically by @PrePersist
    }

    // ==================== JPA Lifecycle Callbacks ====================

    /**
     * Pre-Persist Callback
     * Automatically called by JPA BEFORE inserting a new record into the database
     * Sets both createdAt and updatedAt to current timestamp
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Pre-Update Callback
     * Automatically called by JPA BEFORE updating an existing record
     * Updates the updatedAt timestamp to track when profile was last modified
     * createdAt remains unchanged (it's updatable = false)
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ==================== Getters and Setters ====================

    /**
     * Gets the profile ID (primary key)
     * @return profileId (1 for demo user)
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * Sets the profile ID
     * Note: Usually not called manually - database auto-generates this via @GeneratedValue
     * @param profileId The unique identifier
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * Gets the user's display name
     * @return displayName (e.g., "Alex", "Jordan")
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the user's display name
     * @param displayName New display name (must be 2-50 chars)
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Gets the user's age
     * @return age in years
     */
    public Integer getAge() {
        return age;
    }

    /**
     * Sets the user's age
     * @param age New age (must be 13-120)
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Gets the user's fitness level
     * @return "Beginner", "Intermediate", or "Advanced"
     */
    public String getFitnessLevel() {
        return fitnessLevel;
    }

    /**
     * Sets the user's fitness level
     * @param fitnessLevel Must be "Beginner", "Intermediate", or "Advanced"
     */
    public void setFitnessLevel(String fitnessLevel) {
        this.fitnessLevel = fitnessLevel;
    }

    /**
     * Gets the user's primary fitness goal
     * @return "Strength", "Cardio", "Flexibility", or "Weight Loss"
     */
    public String getPrimaryGoal() {
        return primaryGoal;
    }

    /**
     * Sets the user's primary fitness goal
     * @param primaryGoal Must be "Strength", "Cardio", "Flexibility", or "Weight Loss"
     */
    public void setPrimaryGoal(String primaryGoal) {
        this.primaryGoal = primaryGoal;
    }

    /**
     * Gets the user's available equipment
     * @return Comma-separated list (e.g., "Dumbbells,Resistance Bands") or null if none
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * Sets the user's available equipment
     * @param equipment Comma-separated list or null
     */
    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

    /**
     * Gets the user's weekly workout goal
     * @return Number of days (1-7)
     */
    public Integer getWeeklyGoalDays() {
        return weeklyGoalDays;
    }

    /**
     * Sets the user's weekly workout goal
     * @param weeklyGoalDays Target days per week (1-7)
     */
    public void setWeeklyGoalDays(Integer weeklyGoalDays) {
        this.weeklyGoalDays = weeklyGoalDays;
    }

    /**
     * Gets the profile creation timestamp
     * @return When the profile was first created (never changes)
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Gets the last update timestamp
     * @return When the profile was last modified
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    // ==================== Helper Methods (Business Logic) ====================

    /**
     * Checks if the user is a beginner
     * Used by: BRIX to recommend easier workouts for beginners
     * 
     * @return true if fitnessLevel is "Beginner" (case-insensitive)
     */
    public boolean isBeginner() {
        return "Beginner".equalsIgnoreCase(this.fitnessLevel);
    }

    /**
     * Checks if the user has a specific piece of equipment
     * Used by: Workout filtering (only show workouts user can actually do)
     * 
     * Example: hasEquipment("Dumbbells") returns true if equipment contains "Dumbbells"
     * 
     * @param equipmentName The equipment to check for (case-insensitive)
     * @return true if user has this equipment, false otherwise
     */
    public boolean hasEquipment(String equipmentName) {
        // Return false if user has no equipment listed
        if (this.equipment == null || this.equipment.isEmpty()) {
            return false;
        }
        // Check if equipment string contains the requested item (case-insensitive)
        return this.equipment.toLowerCase().contains(equipmentName.toLowerCase());
    }

    /**
     * Updates multiple profile fields at once
     * Convenience method to avoid calling multiple setters
     * Only updates fields that are not null (allows partial updates)
     * 
     * Used by: PUT /api/v1/profile endpoint when user updates preferences
     * 
     * Example: updateProfile("Jordan", null, "Intermediate", null, null, 5)
     *          → Only updates displayName, fitnessLevel, and weeklyGoalDays
     * 
     * @param displayName New name (or null to keep current)
     * @param age New age (or null to keep current)
     * @param fitnessLevel New fitness level (or null to keep current)
     * @param primaryGoal New goal (or null to keep current)
     * @param equipment New equipment (or null to keep current)
     * @param weeklyGoalDays New weekly goal (or null to keep current)
     */
    public void updateProfile(String displayName, Integer age, String fitnessLevel,
                              String primaryGoal, String equipment, Integer weeklyGoalDays) {
        // Only update non-null values (allows partial updates)
        if (displayName != null) this.displayName = displayName;
        if (age != null) this.age = age;
        if (fitnessLevel != null) this.fitnessLevel = fitnessLevel;
        if (primaryGoal != null) this.primaryGoal = primaryGoal;
        if (equipment != null) this.equipment = equipment;
        if (weeklyGoalDays != null) this.weeklyGoalDays = weeklyGoalDays;
        // Note: updatedAt will be set automatically by @PreUpdate callback
    }

    // ==================== Object Methods (Standard Java Overrides) ====================

    /**
     * String representation of the UserProfile
     * Used for: Logging, debugging
     * 
     * Example output: "UserProfile{profileId=1, displayName='Alex', age=28, 
     *                  fitnessLevel='Intermediate', primaryGoal='Strength', weeklyGoalDays=4}"
     * 
     * @return Human-readable string representation
     */
    @Override
    public String toString() {
        return "UserProfile{" +
                "profileId=" + profileId +
                ", displayName='" + displayName + '\'' +
                ", age=" + age +
                ", fitnessLevel='" + fitnessLevel + '\'' +
                ", primaryGoal='" + primaryGoal + '\'' +
                ", weeklyGoalDays=" + weeklyGoalDays +
                '}';
    }

    /**
     * Checks if two UserProfile objects are equal
     * Two profiles are equal if they have the same profileId
     * Used by: Collections (Set, Map), JPA entity comparisons
     * 
     * @param o Object to compare with
     * @return true if both objects have the same profileId
     */
    @Override
    public boolean equals(Object o) {
        // Check if comparing to itself
        if (this == o) return true;
        // Check if other object is null or different class
        if (o == null || getClass() != o.getClass()) return false;
        // Cast to UserProfile and compare profileIds
        UserProfile that = (UserProfile) o;
        // Two profiles are equal if they have the same non-null profileId
        return profileId != null && profileId.equals(that.profileId);
    }

    /**
     * Generates hash code for this UserProfile
     * Used by: HashMap, HashSet, and other hash-based collections
     * Must be consistent with equals() method
     * 
     * @return Hash code based on the class (ensures all UserProfile instances can be grouped)
     */
    @Override
    public int hashCode() {
        // Use class-based hash code (consistent for all UserProfile instances)
        return getClass().hashCode();
    }
}