package com.b3.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * UserProfile Entity
 * 
 * Represents the single demo user in the B3 application.
 * This is a JPA entity that maps to the "user_profile" table in SQLite.
 * 
 * Design Note: B3 uses a single-user model (no authentication required).
 * The demo user always has profileId = 1, allowing BRIX to personalize
 * coaching based on equipment, fitness level, and goals without login complexity.
 * 
 * Key Features:
 * - Uses type-safe enums instead of String validation (FitnessLevel, PrimaryGoal)
 * - Auto-generates timestamps on create/update via JPA callbacks
 * - Provides helper methods for BRIX logic (isBeginner, hasEquipment)
 * - JSON-friendly with @JsonIgnoreProperties for API flexibility
 * 
 * @author Ben Rickert
 * @version 1.0
 */
@Entity  // Marks this class as a JPA entity (mapped to database table)
@Table(name = "user_profile")  // Specifies exact table name in SQLite
@JsonIgnoreProperties(ignoreUnknown = true)  // Ignores unknown JSON fields from API (forward compatibility)
public class UserProfile {

    // ==================== ENUM TYPES ====================

    /**
     * FitnessLevel Enum
     * 
     * Type-safe representation of user's self-assessed fitness level.
     * Stored in database as STRING (not ordinal) for readability.
     * 
     * Why enum instead of String?
     * - Compile-time safety (can't accidentally use invalid values)
     * - No need for regex validation (@Pattern)
     * - Better IDE autocomplete
     * - Easier refactoring
     * 
     * Used by: BRIX to select appropriate workout difficulty
     */
    public enum FitnessLevel {
        BEGINNER,      // New to fitness or returning after long break
        INTERMEDIATE,  // Regular exerciser (6+ months consistent)
        ADVANCED       // Experienced athlete (2+ years training)
    }

    /**
     * PrimaryGoal Enum
     * 
     * Type-safe representation of user's main fitness objective.
     * Determines BRIX's workout category prioritization.
     * 
     * Examples:
     * - STRENGTH → More resistance training, fewer cardio sessions
     * - CARDIO → More running/HIIT, less heavy lifting
     * - FLEXIBILITY → More stretching/yoga, dynamic mobility
     * - WEIGHT_LOSS → Mix of cardio + strength, higher frequency
     */
    public enum PrimaryGoal {
        STRENGTH,      // Build muscle, increase max lifts
        CARDIO,        // Improve endurance, heart health
        FLEXIBILITY,   // Increase range of motion, mobility
        WEIGHT_LOSS    // Reduce body fat through calorie burn
    }

    // ==================== FIELDS (Database Columns) ====================

    /**
     * Primary Key - Unique identifier for the user profile
     * Auto-generated by database using IDENTITY strategy (SQLite auto-increment)
     * Always 1 for the demo user in MVP
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "profile_id")
    private Long profileId;

    /**
     * Display Name - User's chosen name for the app
     * 
     * Validation: Required, 2-50 characters
     * Used in: Home screen greeting, BRIX messages ("Hey Jordan, ready to build?")
     * 
     * Example: "Alex", "Jordan", "Sam"
     */
    @NotBlank(message = "Display name is required")  // Cannot be null, empty, or whitespace
    @Size(min = 2, max = 50)  // Length constraint
    @Column(name = "display_name", nullable = false, length = 50)
    private String displayName;

    /**
     * Age - User's age in years
     * 
     * Validation: Required, 13-120 (reasonable range)
     * Used by: BRIX to adjust intensity (e.g., more recovery time for older users)
     * 
     * Why validate age?
     * - App targeted at 18-45 demographic
     * - Min 13 for legal reasons (COPPA compliance)
     * - Max 120 for data integrity
     */
    @NotNull(message = "Age is required")
    @Min(13)   // Minimum age 13
    @Max(120)  // Maximum age 120
    @Column(nullable = false)
    private Integer age;

    /**
     * Fitness Level - User's self-assessed experience level
     * 
     * Validation: Required, must be valid FitnessLevel enum
     * Stored as: STRING in database (e.g., "BEGINNER", "INTERMEDIATE")
     * 
     * Used by: BRIX to select workout difficulty
     * - BEGINNER → Easy workouts, longer rest periods
     * - INTERMEDIATE → Medium workouts, standard rest
     * - ADVANCED → Hard workouts, minimal rest
     */
    @NotNull(message = "Fitness level is required")
    @Enumerated(EnumType.STRING)  // Store as string, not ordinal number
    @Column(name = "fitness_level", nullable = false, length = 20)
    private FitnessLevel fitnessLevel;

    /**
     * Primary Goal - User's main fitness objective
     * 
     * Validation: Required, must be valid PrimaryGoal enum
     * Stored as: STRING in database (e.g., "STRENGTH", "CARDIO")
     * 
     * Used by: BRIX to prioritize workout categories
     * Example: If goal is WEIGHT_LOSS, BRIX recommends more cardio/HIIT
     */
    @NotNull(message = "Primary goal is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "primary_goal", nullable = false, length = 30)
    private PrimaryGoal primaryGoal;

    /**
     * Equipment - Available workout equipment (comma-separated)
     * 
     * Validation: Optional (user might only do bodyweight exercises)
     * Format: Comma-separated string (e.g., "Dumbbells,Resistance Bands,Pull-up Bar")
     * 
     * Used by: Workout filtering (only show workouts user can actually do)
     * Example: If equipment = "Dumbbells", hide "Pull-up Bar" workouts
     * 
     * Why comma-separated instead of separate table?
     * - Keeps MVP simple (no Equipment entity needed)
     * - Easy to parse in code (equipment.contains("Dumbbells"))
     * - Can refactor to many-to-many relationship later if needed
     */
    @Column(name = "equipment", length = 200)
    private String equipment;

    /**
     * Weekly Goal Days - Target number of workout days per week
     * 
     * Validation: Required, 1-7 days
     * Used by: Progress tracking, consistency calculations
     * 
     * Example calculation:
     * - If goal is 4 days/week and user completes 3 workouts → 75% consistency
     * - BRIX uses this to determine if user is "on track" or "struggling"
     */
    @NotNull(message = "Weekly goal days is required")
    @Min(1)    // At least 1 day per week
    @Max(7)    // Max 7 days per week
    @Column(name = "weekly_goal_days", nullable = false)
    private Integer weeklyGoalDays;

    /**
     * Created At - Timestamp when profile was first created
     * 
     * Auto-populated by: @PrePersist callback (onCreate method below)
     * updatable = false: This value never changes after initial insert
     * 
     * Used for: Account age tracking, data integrity
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Updated At - Timestamp when profile was last modified
     * 
     * Auto-updated by: @PreUpdate callback (onUpdate method below)
     * 
     * Used for: Tracking when user last changed preferences
     * Example: If user hasn't updated profile in 6 months, BRIX might suggest reviewing goals
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ==================== CONSTRUCTORS ====================

    /**
     * Default Constructor (Required by JPA)
     * 
     * JPA uses reflection to create entity instances when loading from database.
     * Never call this constructor directly - use the parameterized constructor instead.
     */
    public UserProfile() {}

    /**
     * Parameterized Constructor - Creates a new UserProfile with all required fields
     * 
     * Use this when creating a new user profile (e.g., during onboarding).
     * Timestamps (createdAt, updatedAt) are set automatically via @PrePersist.
     * 
     * @param displayName User's display name (2-50 chars)
     * @param age User's age (13-120)
     * @param fitnessLevel BEGINNER, INTERMEDIATE, or ADVANCED
     * @param primaryGoal STRENGTH, CARDIO, FLEXIBILITY, or WEIGHT_LOSS
     * @param equipment Comma-separated list (e.g., "Dumbbells,Bands") or null
     * @param weeklyGoalDays Target workout days per week (1-7)
     */
    public UserProfile(String displayName, Integer age, FitnessLevel fitnessLevel,
                       PrimaryGoal primaryGoal, String equipment, Integer weeklyGoalDays) {
        this.displayName = displayName;
        this.age = age;
        this.fitnessLevel = fitnessLevel;
        this.primaryGoal = primaryGoal;
        this.equipment = equipment;
        this.weeklyGoalDays = weeklyGoalDays;
        // Note: createdAt and updatedAt are set automatically by @PrePersist
    }

    // ==================== JPA LIFECYCLE CALLBACKS ====================

    /**
     * Pre-Persist Callback
     * 
     * Automatically called by JPA BEFORE inserting a new record into the database.
     * Sets both createdAt and updatedAt to the current timestamp.
     * 
     * Why set both?
     * - createdAt = when the record was born (never changes)
     * - updatedAt = when it was last modified (starts same as createdAt)
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Pre-Update Callback
     * 
     * Automatically called by JPA BEFORE updating an existing record.
     * Updates the updatedAt timestamp to track when profile was last modified.
     * 
     * createdAt remains unchanged (it's marked updatable = false).
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ==================== GETTERS & SETTERS ====================

    /**
     * Gets the profile ID (primary key)
     * @return profileId (1 for demo user in MVP)
     */
    public Long getProfileId() { return profileId; }

    /**
     * Sets the profile ID
     * Note: Usually not called manually - database auto-generates via @GeneratedValue
     * @param profileId The unique identifier
     */
    public void setProfileId(Long profileId) { this.profileId = profileId; }

    /**
     * Gets the user's display name
     * @return displayName (e.g., "Alex", "Jordan")
     */
    public String getDisplayName() { return displayName; }

    /**
     * Sets the user's display name
     * @param displayName New display name (must be 2-50 chars)
     */
    public void setDisplayName(String displayName) { this.displayName = displayName; }

    /**
     * Gets the user's age
     * @return age in years
     */
    public Integer getAge() { return age; }

    /**
     * Sets the user's age
     * @param age New age (must be 13-120)
     */
    public void setAge(Integer age) { this.age = age; }

    /**
     * Gets the user's fitness level
     * @return FitnessLevel enum (BEGINNER, INTERMEDIATE, or ADVANCED)
     */
    public FitnessLevel getFitnessLevel() { return fitnessLevel; }

    /**
     * Sets the user's fitness level
     * @param fitnessLevel Must be valid FitnessLevel enum
     */
    public void setFitnessLevel(FitnessLevel fitnessLevel) { this.fitnessLevel = fitnessLevel; }

    /**
     * Gets the user's primary fitness goal
     * @return PrimaryGoal enum (STRENGTH, CARDIO, FLEXIBILITY, or WEIGHT_LOSS)
     */
    public PrimaryGoal getPrimaryGoal() { return primaryGoal; }

    /**
     * Sets the user's primary fitness goal
     * @param primaryGoal Must be valid PrimaryGoal enum
     */
    public void setPrimaryGoal(PrimaryGoal primaryGoal) { this.primaryGoal = primaryGoal; }

    /**
     * Gets the user's available equipment
     * @return Comma-separated list (e.g., "Dumbbells,Resistance Bands") or null if none
     */
    public String getEquipment() { return equipment; }

    /**
     * Sets the user's available equipment
     * @param equipment Comma-separated list or null
     */
    public void setEquipment(String equipment) { this.equipment = equipment; }

    /**
     * Gets the user's weekly workout goal
     * @return Number of days (1-7)
     */
    public Integer getWeeklyGoalDays() { return weeklyGoalDays; }

    /**
     * Sets the user's weekly workout goal
     * @param weeklyGoalDays Target days per week (1-7)
     */
    public void setWeeklyGoalDays(Integer weeklyGoalDays) { this.weeklyGoalDays = weeklyGoalDays; }

    /**
     * Gets the profile creation timestamp
     * @return When the profile was first created (never changes)
     */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /**
     * Gets the last update timestamp
     * @return When the profile was last modified
     */
    public LocalDateTime getUpdatedAt() { return updatedAt; }

    // ==================== BUSINESS LOGIC (Helper Methods) ====================

    /**
     * Checks if the user is a beginner
     * 
     * Used by: BRIX to recommend easier workouts for beginners
     * Example: If isBeginner() → recommend "Bodyweight Basics" instead of "Advanced HIIT"
     * 
     * Why enum comparison instead of string?
     * - Type-safe: fitnessLevel == FitnessLevel.BEGINNER (not error-prone string comparison)
     * - More efficient: enum comparison is faster than string comparison
     * 
     * @return true if fitnessLevel is BEGINNER, false otherwise
     */
    public boolean isBeginner() {
        return this.fitnessLevel == FitnessLevel.BEGINNER;
    }

    /**
     * Checks if the user has a specific piece of equipment
     * 
     * Used by: Workout filtering (only show workouts user can actually do)
     * Example: If user hasEquipment("Dumbbells"), show dumbbell workouts
     * 
     * How it works:
     * 1. Returns false if equipment is null or empty (user has no equipment)
     * 2. Converts both equipment string and search term to lowercase (case-insensitive)
     * 3. Checks if equipment string contains the search term
     * 
     * Example calls:
     * - hasEquipment("Dumbbells") → true if equipment = "Dumbbells,Resistance Bands"
     * - hasEquipment("dumbbells") → true (case-insensitive)
     * - hasEquipment("Pull-up Bar") → false if not in equipment list
     * 
     * @param equipmentName The equipment to check for (case-insensitive)
     * @return true if user has this equipment, false otherwise
     */
    public boolean hasEquipment(String equipmentName) {
        // Return false if user has no equipment listed
        if (this.equipment == null || this.equipment.isBlank()) return false;
        // Check if equipment string contains the requested item (case-insensitive)
        return this.equipment.toLowerCase().contains(equipmentName.toLowerCase());
    }

    /**
     * Updates multiple profile fields at once
     * 
     * Convenience method to avoid calling multiple setters individually.
     * Only updates fields that are not null (allows partial updates).
     * 
     * Used by: PUT /api/v1/profile endpoint when user updates preferences
     * 
     * Why partial updates?
     * - Frontend might only send changed fields (not entire profile)
     * - Example: User only changes fitnessLevel from BEGINNER to INTERMEDIATE
     *   → Only fitnessLevel is updated, other fields remain unchanged
     * 
     * Example usage:
     * ```java
     * userProfile.updateProfile(
     *     "Jordan",              // New name
     *     null,                  // Keep current age
     *     FitnessLevel.INTERMEDIATE,  // Level up!
     *     null,                  // Keep current goal
     *     "Dumbbells,Bands",     // Added resistance bands
     *     5                      // Increase to 5 days/week
     * );
     * ```
     * 
     * @param displayName New name (or null to keep current)
     * @param age New age (or null to keep current)
     * @param fitnessLevel New fitness level (or null to keep current)
     * @param primaryGoal New goal (or null to keep current)
     * @param equipment New equipment (or null to keep current)
     * @param weeklyGoalDays New weekly goal (or null to keep current)
     */
    public void updateProfile(String displayName, Integer age, FitnessLevel fitnessLevel,
                              PrimaryGoal primaryGoal, String equipment, Integer weeklyGoalDays) {
        // Only update non-null values (partial update support)
        if (displayName != null) this.displayName = displayName;
        if (age != null) this.age = age;
        if (fitnessLevel != null) this.fitnessLevel = fitnessLevel;
        if (primaryGoal != null) this.primaryGoal = primaryGoal;
        if (equipment != null) this.equipment = equipment;
        if (weeklyGoalDays != null) this.weeklyGoalDays = weeklyGoalDays;
        // Note: updatedAt will be set automatically by @PreUpdate callback
    }

    // ==================== OBJECT OVERRIDES (Standard Java) ====================

    /**
     * String representation of the UserProfile
     * 
     * Used for: Logging, debugging, toString() in log statements
     * 
     * Example output:
     * "UserProfile{profileId=1, displayName='Alex', age=28, 
     *  fitnessLevel=INTERMEDIATE, primaryGoal=STRENGTH, weeklyGoalDays=4}"
     * 
     * Why override toString()?
     * - Default Object.toString() shows memory address (not useful)
     * - This shows actual field values for debugging
     * - Follows standard Java convention
     * 
     * @return Human-readable string representation
     */
    @Override
    public String toString() {
        return "UserProfile{" +
                "profileId=" + profileId +
                ", displayName='" + displayName + '\'' +
                ", age=" + age +
                ", fitnessLevel=" + fitnessLevel +
                ", primaryGoal=" + primaryGoal +
                ", weeklyGoalDays=" + weeklyGoalDays +
                '}';
    }

    /**
     * Checks if two UserProfile objects are equal
     * 
     * Two profiles are considered equal if they have the same profileId.
     * 
     * Used by: Collections (Set, Map), JPA entity comparisons
     * Example: userProfileSet.contains(someProfile) uses this method
     * 
     * Why override equals()?
     * - Default Object.equals() compares memory addresses (not useful for entities)
     * - JPA needs this to determine if two entities represent the same database row
     * - Required when using entities in HashSet, HashMap, etc.
     * 
     * Why use instanceof instead of getClass()?
     * - instanceof allows subclass equality (more flexible)
     * - Recommended by Hibernate documentation
     * 
     * @param o Object to compare with
     * @return true if both objects have the same profileId, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        // Fast path: comparing to itself
        if (this == o) return true;
        // Check if other object is null or not a UserProfile
        if (!(o instanceof UserProfile)) return false;
        // Cast to UserProfile and compare profileIds
        UserProfile that = (UserProfile) o;
        // Two profiles are equal if they have the same non-null profileId
        return Objects.equals(profileId, that.profileId);
    }

    /**
     * Generates hash code for this UserProfile
     * 
     * Used by: HashMap, HashSet, and other hash-based collections
     * Must be consistent with equals() method (if equals() is true, hashCode() must match)
     * 
     * Why override hashCode()?
     * - Required when overriding equals() (Java contract)
     * - Used by HashMap to efficiently locate objects
     * - Objects.hash() is a clean utility that handles null values
     * 
     * Why hash on profileId only?
     * - profileId uniquely identifies the entity
     * - Consistent with equals() implementation
     * - Won't change (profileId is immutable after creation)
     * 
     * @return Hash code based on profileId
     */
    @Override
    public int hashCode() {
        // Use Objects.hash() utility for clean, null-safe hashing
        return Objects.hash(profileId);
    }
}